name: FireworkParade
main: de.eldoria.fireworkparade.FireworkParade
version: 1.0-BETA
api-version: 1.13
commands:
  fireworkparade:
    aliases:
      - fp
    description: Get a defined firework
    permission: fireworkfun.give
  fireworkcreator:
    aliases:
      - fpc